timestamp = 0
prevhash = "0x44915be5b6c20b0678cf05fcddbbaa832e25d7e6ac538784cd5c24de00d47472"

[[services]]
name = "asset"
payload = '''
{
    "id": "0xf56924db538e77bb5951eb5ff0d02b88983c49c45eea30e8ae3e7234b311436c",
    "name": "HT",
    "symbol": "HT",
    "supply": 50000000000000000,
    "precision": 8,
    "init_mints": [{"addr": "muta10e0525sfrf53yh2aljmm3sn9jq5njk7llt9agp", "balance": 50000000000000000}],
    "admin": "muta10e0525sfrf53yh2aljmm3sn9jq5njk7llt9agp",
    "relayable": true
}
'''

[[services]]
name = "metadata"
payload = '''
{
    "chain_id": "0xb6a4d7da21443f5e816e8700eea87610e6d769657d6b8ec73028457bf2ca4036",
    "bech32_address_hrp": "muta",
    "common_ref": "0x703873635a6b51513451",
    "timeout_gap": 99999,
    "cycles_limit": 999999999999,
    "cycles_price": 1,
    "interval": 3000,
    "verifier_list": [
       {
           "bls_pub_key": "0x04102947214862a503c73904deb5818298a186d68c7907bb609583192a7de6331493835e5b8281f4d9ee705537c0e765580e06f86ddce5867812fceb42eecefd209f0eddd0389d6b7b0100f00fb119ef9ab23826c6ea09aadcc76fa6cea6a32724",
           "pub_key": "0x02ef0cb0d7bc6c18b4bea1f5908d9106522b35ab3c399369605d4242525bda7e60",
           "address": "muta14e0lmgck835vm2dfm0w3ckv6svmez8fdgdl705",
           "propose_weight": 1,
           "vote_weight": 1
       }
    ],
    "propose_ratio": 15,
    "prevote_ratio": 10,
    "precommit_ratio": 10,
    "brake_ratio": 7,
    "tx_num_limit": 9000,
    "max_tx_size": 10485760
}
'''

[[services]]
name = "governance"
payload = '''
{
    "info": {
        "admin": "muta10e0525sfrf53yh2aljmm3sn9jq5njk7llt9agp",
        "tx_failure_fee": 1000,
        "tx_floor_fee": 100,
        "profit_deduct_rate_per_million": 10,
        "tx_fee_discount": [
            {"threshold": 10, "discount_percent": 10}
        ],
        "miner_benefit": 3
    },
    "tx_fee_inlet_address": "muta19dddt3retspx298cx9785g27yxxue4k0zmetx3",
    "miner_profit_outlet_address": "muta1dqf7hymzxuhw7csq7wcahslcr9n3ewnfz42ts0",
    "miner_charge_map": [
        {"address": "muta1dqf7hymzxuhw7csq7wcahslcr9n3ewnfz42ts0", "miner_charge_address": "muta1dqf7hymzxuhw7csq7wcahslcr9n3ewnfz42ts0"}
    ]
}
'''

# # you can enable whitelist in riscv with init payload below
# [[services]]
# name = 'riscv'
# payload = '''
# {
#     "enable_authorization": true,
#     "admins": ["muta1elcsqgg8zp2xp9ql09uz3argvea2rgkmglwr47"],
#     "deploy_auth": ["muta1nnx2ewu2fvp484pp8psnktdh944xv885nkwpvu"]
# }
# '''

[[services]]
name = "kyc"
payload = '''
{
   "org_name": "huobi",
   "org_description": "",
   "org_admin": "muta10e0525sfrf53yh2aljmm3sn9jq5njk7llt9agp",
   "supported_tags": [ "name", "gender", "age" ],
   "service_admin": "muta10e0525sfrf53yh2aljmm3sn9jq5njk7llt9agp"
}
'''

[[services]]
name = "admission_control"
payload = '''
{
   "admin": "muta10e0525sfrf53yh2aljmm3sn9jq5njk7llt9agp",
   "deny_list": [ "muta16tfxsaylle2daa8zuul9up4ya0cddav9h4chyk" ]
}
'''
